### ISSUE TITLE
Wireframes Backoffice Order Management System

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/backoffice-ordering-system#6]
Figma:
https://www.figma.com/design/1dAetyLUY41HNERhCwrrQL/BOS?node-id=9027-3454&t=V5UbJSrlfm2v14nT-1

 
3. Unified Login and Registration PanelCreate a unified interface for login and registration, shared between WL and BOS.Ensure a cohesive user experience with standardized design elements.
2. Provider View
2.1. Order List
Display a list of all orders assigned to the Provider.
Include sorting and filtering options specific to Provider needs.
2.2. Mini Order View
Provide a compact view of order details, accessible directly from the list.
3. Order Details View (with Comments)
Display detailed information about an order.
Include a section for comments and activity logs related to the order.
4. Coordinator View
4.1. Order List
Display a list of all orders with advanced filtering options.
Filters should differ from those available to the Provider, catering to Coordinator-specific workflows.
4.2. Mini Order View
Provide a compact view of order details tailored for the Coordinator role.
4.3. Full Order View
Include options to add or remove Providers assigned to an order.
5. Admin Views
5.1. User List View
Display a list of all users with the following details:
Full Name
Email
Associated Provider (if any)
Role (Admin, Provider, Coordinator, or None)
Include functionalities for:
Adding a new user.
Filtering users by role or Provider.
5.2. User Detail View
Display the following information:
Full Name
Email
Role
Associated Provider (if applicable)
Provide options for:
Role modification.
Deleting the user.
5.3. Provider View
Display Provider-specific details, including a list of assigned users.
Include functionalities for adding and removing users from a Provider.

**Comment by Michal-Kolomanski** [comment]
done
